import io
import re
from html import unescape
from urllib.parse import urlparse, quote_plus

import feedparser
import pandas as pd
import requests
from PIL import Image
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer


OFFICIAL_HINTS = {
    ".gov",
    ".gov.uk",
    ".europa.eu",
    ".int",
    ".edu",
    ".ac.uk",
    ".ac.jp",
    ".gov.om",
}

REPUTABLE_NEWS_HINTS = {
    "reuters.com",
    "apnews.com",
    "bbc.com",
    "bbc.co.uk",
    "ft.com",
    "bloomberg.com",
}

SYNTHETIC_MARKERS = {
    "ai generated",
    "ai-generated",
    "generated by ai",
    "synthetic media",
    "midjourney",
    "dall-e",
    "dalle",
    "stable diffusion",
    "adobe firefly",
    "content credentials",
    "c2pa",
}


def normalize_text(value):
    return re.sub(
        r"\s+",
        " ",
        str(value or ""),
    ).strip()


def tokenize(value):
    return set(
        token.lower()
        for token in re.findall(
            r"[A-Za-z0-9][A-Za-z0-9\-]{2,}",
            normalize_text(value),
        )
    )


def text_similarity(left, right):
    left_tokens = tokenize(left)
    right_tokens = tokenize(right)

    if not left_tokens or not right_tokens:
        return 0.0

    intersection = len(left_tokens & right_tokens)
    union = len(left_tokens | right_tokens)

    return round(
        intersection / union,
        4,
    ) if union else 0.0


def domain_from_url(url):
    try:
        return (
            urlparse(url).netloc.lower()
            .replace("www.", "")
        )
    except Exception:
        return ""


def source_credibility_score(url="", source_name=""):
    domain = domain_from_url(url)
    source_text = (
        f"{domain} {source_name}"
    ).lower()

    if not source_text.strip():
        return 35.0, "No source information supplied"

    if any(
        hint in source_text
        for hint in OFFICIAL_HINTS
    ):
        return 92.0, "Official or institutional source"

    if any(
        hint in source_text
        for hint in REPUTABLE_NEWS_HINTS
    ):
        return 82.0, "Established news source"

    if domain:
        return 55.0, "Identifiable public web source"

    return 40.0, "Source cannot be reliably classified"


def search_google_news(claim, limit=15):
    encoded = quote_plus(
        normalize_text(claim)[:220]
    )

    feed = feedparser.parse(
        "https://news.google.com/rss/search?"
        f"q={encoded}&hl=en-US&gl=US&ceid=US:en"
    )

    rows = []

    for entry in feed.entries[:limit]:
        title = normalize_text(entry.title)
        link = getattr(entry, "link", "")
        source = ""

        source_data = getattr(
            entry,
            "source",
            None,
        )

        if source_data:
            try:
                source = source_data.get(
                    "title",
                    "",
                )
            except Exception:
                source = ""

        rows.append(
            {
                "Headline": title,
                "Source": source,
                "Link": link,
                "Similarity": text_similarity(
                    claim,
                    title,
                ),
            }
        )

    if not rows:
        return pd.DataFrame(
            columns=[
                "Headline",
                "Source",
                "Link",
                "Similarity",
            ]
        )

    return (
        pd.DataFrame(rows)
        .sort_values(
            "Similarity",
            ascending=False,
        )
        .reset_index(drop=True)
    )


def fetch_url_evidence(url):
    if not url:
        return {
            "ok": False,
            "domain": "",
            "title": "",
            "text": "",
            "metadata": {},
            "error": "No URL supplied",
        }

    try:
        response = requests.get(
            url,
            headers={
                "User-Agent": (
                    "TrustIntelAI-VerificationPrototype/0.1"
                )
            },
            timeout=20,
        )
        response.raise_for_status()
    except Exception as error:
        return {
            "ok": False,
            "domain": domain_from_url(url),
            "title": "",
            "text": "",
            "metadata": {},
            "error": str(error),
        }

    html = response.text[:600000]

    title_match = re.search(
        r"<title[^>]*>(.*?)</title>",
        html,
        flags=re.I | re.S,
    )
    title = (
        normalize_text(
            unescape(title_match.group(1))
        )
        if title_match
        else ""
    )

    meta_pairs = re.findall(
        r'<meta[^>]+(?:name|property)=["\']([^"\']+)["\'][^>]+content=["\']([^"\']*)["\']',
        html,
        flags=re.I,
    )

    metadata = {
        normalize_text(key).lower():
        normalize_text(unescape(value))
        for key, value in meta_pairs
    }

    stripped = re.sub(
        r"<script.*?</script>|<style.*?</style>",
        " ",
        html,
        flags=re.I | re.S,
    )
    stripped = re.sub(
        r"<[^>]+>",
        " ",
        stripped,
    )
    text = normalize_text(
        unescape(stripped)
    )[:20000]

    return {
        "ok": True,
        "domain": domain_from_url(url),
        "title": title,
        "text": text,
        "metadata": metadata,
        "error": "",
    }


def synthetic_text_signals(text, metadata=None):
    metadata = metadata or {}
    combined = " ".join(
        [
            normalize_text(text),
            " ".join(
                f"{key} {value}"
                for key, value
                in metadata.items()
            ),
        ]
    ).lower()

    declared_markers = [
        marker
        for marker in SYNTHETIC_MARKERS
        if marker in combined
    ]

    if declared_markers:
        return {
            "label": "Declared or provenance-linked synthetic signal",
            "score": 85.0,
            "confidence": "High",
            "evidence": ", ".join(
                sorted(declared_markers)
            ),
        }

    text_only = normalize_text(text)
    if not text_only:
        return {
            "label": "Unknown",
            "score": 0.0,
            "confidence": "Low",
            "evidence": "No content available",
        }

    sentences = [
        sentence.strip()
        for sentence in re.split(
            r"[.!?]+",
            text_only,
        )
        if sentence.strip()
    ]

    if len(sentences) < 4:
        return {
            "label": "Unknown",
            "score": 15.0,
            "confidence": "Low",
            "evidence": (
                "Insufficient provenance evidence. "
                "Text style alone cannot establish AI origin."
            ),
        }

    lengths = [
        len(sentence.split())
        for sentence in sentences
    ]

    mean_length = sum(lengths) / len(lengths)
    variance = (
        sum(
            (length - mean_length) ** 2
            for length in lengths
        )
        / len(lengths)
    )

    uniformity = max(
        0.0,
        1.0 - min(
            1.0,
            (variance ** 0.5) / 18.0,
        ),
    )

    score = round(
        20 + 20 * uniformity,
        2,
    )

    return {
        "label": "No reliable synthetic provenance detected",
        "score": score,
        "confidence": "Low",
        "evidence": (
            "Only weak stylistic signals are available. "
            "Do not treat this as proof of AI generation."
        ),
    }


def inspect_image_provenance(file_bytes):
    if not file_bytes:
        return {
            "label": "Unknown",
            "score": 0.0,
            "confidence": "Low",
            "evidence": "No image supplied",
            "metadata": {},
        }

    try:
        image = Image.open(
            io.BytesIO(file_bytes)
        )
        exif = image.getexif()
    except Exception as error:
        return {
            "label": "Unknown",
            "score": 0.0,
            "confidence": "Low",
            "evidence": f"Image metadata could not be read: {error}",
            "metadata": {},
        }

    metadata = {
        str(key): normalize_text(value)
        for key, value in exif.items()
    }

    combined = " ".join(
        metadata.values()
    ).lower()

    markers = [
        marker
        for marker in SYNTHETIC_MARKERS
        if marker in combined
    ]

    if markers:
        return {
            "label": "Synthetic provenance marker detected",
            "score": 90.0,
            "confidence": "High",
            "evidence": ", ".join(markers),
            "metadata": metadata,
        }

    software_markers = [
        term
        for term in [
            "photoshop",
            "lightroom",
            "gimp",
            "canva",
        ]
        if term in combined
    ]

    if software_markers:
        return {
            "label": "Edited media metadata detected",
            "score": 45.0,
            "confidence": "Medium",
            "evidence": ", ".join(
                software_markers
            ),
            "metadata": metadata,
        }

    return {
        "label": "No synthetic provenance marker found",
        "score": 10.0,
        "confidence": "Low",
        "evidence": (
            "Absence of metadata is not proof of authenticity."
        ),
        "metadata": metadata,
    }


def verification_assessment(
    claim,
    source_url="",
    source_name="",
    evidence_df=None,
    fetched=None,
):
    claim = normalize_text(claim)
    evidence_df = (
        evidence_df
        if evidence_df is not None
        else pd.DataFrame()
    )
    fetched = fetched or {}

    credibility, credibility_note = (
        source_credibility_score(
            source_url,
            source_name,
        )
    )

    similarities = (
        evidence_df["Similarity"].tolist()
        if (
            not evidence_df.empty
            and "Similarity" in evidence_df
        )
        else []
    )

    strong_matches = len(
        [
            value
            for value in similarities
            if value >= 0.18
        ]
    )
    moderate_matches = len(
        [
            value
            for value in similarities
            if value >= 0.10
        ]
    )

    evidence_coverage = min(
        100.0,
        strong_matches * 22
        + max(
            0,
            moderate_matches
            - strong_matches,
        ) * 8,
    )

    source_similarity = 0.0
    if fetched.get("ok"):
        source_similarity = max(
            text_similarity(
                claim,
                fetched.get("title", ""),
            ),
            text_similarity(
                claim,
                fetched.get("text", "")[:4000],
            ),
        )

    factual_reliability = min(
        100.0,
        0.45 * credibility
        + 0.40 * evidence_coverage
        + 0.15 * min(
            100.0,
            source_similarity * 300,
        ),
    )

    if factual_reliability >= 75:
        status = "Supported"
    elif factual_reliability >= 55:
        status = "Partially supported"
    elif factual_reliability >= 35:
        status = "Unverified"
    else:
        status = "Weakly supported / disputed"

    if evidence_coverage >= 60:
        confidence = "High"
    elif evidence_coverage >= 25:
        confidence = "Medium"
    else:
        confidence = "Low"

    return {
        "Status": status,
        "FRS": round(
            factual_reliability,
            2,
        ),
        "SCS": round(
            credibility,
            2,
        ),
        "ECS": round(
            evidence_coverage,
            2,
        ),
        "Verification Confidence": confidence,
        "Source Note": credibility_note,
        "Strong Corroborations": strong_matches,
        "Moderate Corroborations": moderate_matches,
    }


def claim_sentiment(claim):
    analyzer = SentimentIntensityAnalyzer()
    return round(
        analyzer.polarity_scores(
            normalize_text(claim)
        )["compound"],
        3,
    )
